---
version: "2.1"
services:
  romvault:
    image: laromicas/romvault
    container_name: romvault
    volumes:
      - /unsorted/jdownloader/chd-convert:/tmp/images/:rw
      - /docker/appdata/romvault:/config:rw \
      - /home/user/ROMVault/DatRoot:/config/DatRoot:rw \
      - /home/user/ROMVault/RomRoot:/config/RomRoot:rw \
      - /home/user/ROMVault/ToSort:/config/ToSort:rw \
    ports:
      - 5800:5800
    stdin_open: true    # to attach to containers
    tty: true           # also used to attach to containers
#    network_mode: service:wireguard     # To run through vpn service container, in turn UI port must be forwarded inside vpn. No local access unless otherwise defined
    networks:           # Specify network for container
      - homelab
networks:    # I don't know why but you have to specify the network 2x. In service, and in this tag area..
  homelab:
    external: true      # This option causes compose to join the above network instead of making a _default one (supposedly)