---
version: "2.1"
services:
  paperless-ng:
    image: lscr.io/linuxserver/paperless-ng:latest
    container_name: paperless-ng
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - REDIS_URL= #optional
    volumes:
      - </path/to/appdata/config>:/config
      - </path/to/appdata/data>:/data
    ports:
      - 8000:8000
    restart: unless-stopped