---
version: "2.1"
services:
  dillinger:
    image: lscr.io/linuxserver/dillinger:latest
    container_name: dillinger
    environment:
      - PUID=1000
      - PGID=1006
      - TZ=America/New_York
    volumes:
      - /docker-containers/dillinger:/config
      - /Documents/prodigy/Text-Files:/mediadata
    ports:
      - 8281:8080
    restart: unless-stopped
    stdin_open: true    # to attach to containers
    tty: true           # also used to attach to containers
#    network_mode: service:wireguard     # To run through vpn service container, in turn UI port must be forwarded inside vpn. No local access unless otherwise defined
    networks:           # Specify network for container
      - homelab
networks:    # I don't know why but you have to specify the network 2x. In service, and in this tag area..
#  some-additional-network:
#     aliases:
#        - simplename   # This isn't allowed in portainer, must be called in the service.
  homelab:
#    name: homelab      # Networks can also be given a custom name, not needed if existing
    external: true      # This option causes compose to join the above network instead of making a _default one (supposedly)