---
version: "2.1"
services:
  organizr:
    image: organizr/organizr
    container_name: organizr
    environment:
      - branch=v2-master
      - PUID=1000
      - PGID=1003
      - TZ=GMT-5
    volumes:
      - /docker-containers/organizr:/config
    ports:
      - 9983:80
    restart: unless-stopped