services:
  lancommander:
    image: lancommander/lancommander:latest
    container_name: lancommander
    environment:
      - PUID=1000
      - PGID=1006
      - TZ=America/New_York
    volumes:
      - /docker-containers/lancommander/config:/app/config
      - /games:/media/games
      - /unsorted:/media/unsorted
    ports:
      - 1337:1337/tcp   # Webinterface
      - 35891:35891/udp # Beacon Broadcast
    restart: unless-stopped
#    network_mode: service:wireguard     # To run through vpn service container, in turn UI port must be forwarded inside vpn. No local access unless otherwise defined
    networks:           # Specify network for container
      - homelab
networks:    # I don't know why but you have to specify the network 2x. In service, and in this tag area..
  homelab:
    external: true      # This option causes compose to join the above network instead of making a _default one (supposedly)