version: "2.1"
services:
  podgrab:
    image: akhilrex/podgrab
    container_name: podgrab
    environment:
      - CHECK_FREQUENCY=240
      #- PASSWORD=ChangeMe123     ## Uncomment to enable basic authentication, username = podgrab
    volumes:
      - /docker-containers/podgrab:/config
      - /Music/Podcasts:/assets
    ports:
      - 8182:8080
    restart: unless-stopped
    stdin_open: true    # to attach to containers
    tty: true           # also used to attach to containers
    networks:           # Specify network for container
      - homelab
networks:    # I don't know why but you have to specify the network 2x. In service, and in this tag area..
  homelab:
    external: true      # This option causes compose to join the above network instead of making a _default one (supposedly)